spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: 
    username:
    password:

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true

jwt:
  secret-key: QzQlU1lAVkpcXiFaSlxRND5cQkQyRjdGVDZIR0QjPWRFV0ZeWCJdUVZaSCk1TltBXF4=
  token:
    access: 86400000
    refresh: 864000000
